export const NETWORK = {
  network: 'TESTNET',
  networkPassphrase: 'Test SDF Network ; September 2015',
  rpcUrl: 'https://soroban-testnet.stellar.org',
  horizonUrl: 'https://horizon-testnet.stellar.org',
};

export const CONTRACTS = {
  COHORT_CONTRACT_ID: import.meta.env.VITE_COHORT_CONTRACT_ID || 'CD54FDYS47GEYUONKXHWGYL7ULGWS7NPRJU45YYYKUUHMHIAJYVT7I5Q',
  ATTENDANCE_CONTRACT_ID: import.meta.env.VITE_ATTENDANCE_CONTRACT_ID || 'CCRUCGYIQVO4XDAGV7ALUHV5QQG3WXKO6G33VGOKGHMPZR5SZ3G2YESX',
  STAKE_TOKEN_ID: import.meta.env.VITE_NATIVE_TOKEN_ID || import.meta.env.VITE_STAKE_TOKEN_ID || 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
};
